#! /bin/sh


MONITOR_LIST=$(xrandr --listmonitors | sed '1 d' | awk 'NF>1{print $NF}')

i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor -d $monitor/1 $monitor/2 $monitor/3 $monitor/4 $monitor/5 $monitor/6 $monitor/7 $monitor/8 $monitor/9 $monitor/10
    let i++
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a polybar state=sticky

bspc config initial_polarity second_child

# Autostart
killall sxhkd
sxhkd &

killall compton
compton --config ~/.config/compton/compton.conf &

~/bin/wallpaper.sh -b ~/Wallpapers/lukesmith/Titans

~/.config/polybar/launch.sh
dex -a -e bspwm



