#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a polybar state=sticky

# Autostart
compton --config ~/.config/compton/compton.conf &

SCREENS=$(xrandr -d :0 -q | grep -c ' connected')
if (( SCREENS > 1 )); then
    ~/bin/wallpaper.sh -w -b ~/Wallpapers/widescreen_wallpapers
else
    ~/bin/wallpaper.sh -b ~/Wallpapers/lukesmith/Titans
fi

~/.config/polybar/launch.sh
dex -a



